# Main menu navigation 
# --------------------------------------

# format: name: link || icon
# sub-menu
# name || icon:
#   name || link || icon

menu:
  # Home: / || fas fa-home
  # Archives: /archives/ || fas fa-archive
  # Tags: /tags/ || fas fa-tags
  # Categories: /categories/ || fas fa-folder-open
  # List||fas fa-list:
  #   - Music || /music/ || fas fa-music
  #   - Movie || /movies/ || fas fa-video
  # Link: /link/ || fas fa-link
  # About: /about/ || fas fa-heart

# Code Blocks 
# --------------------------------------

highlight_theme: light # default / darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
code_word_wrap: false

# copy settings
copy:
  enable: true

# social settings 
# formal:
#   icon: link || the description
social:
  # fab fa-github: https://github.com/xxxxx || Github
  # fas fa-envelope: mailto:xxxxxx@gmail.com || Email

# search 
# --------------------------------------

# Algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
    hits_stats: '${hits} results found in ${time} ms'

# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

# Image
# --------------------------------------

# Favicon
favicon: 

# Avatar 
avatar:
  img: 

# the banner image of home page
index_img: 

# if the banner of page not setting, it will show the top_img
default_top_img: 

# the banner image of archive page
archive_img:

# the banner image of tag page
# note: tag page, not tags page 
tag_img:

# the banner image of category page
# note: category page, not categories page 
category_img:

cover:
  # display the cover or not 
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page 
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed
  default_cover:

# Replace Broken Images 
error_img:
  flink: /image/friend_404.gif
  post_page: /image/404.jpg

# A simple 404 page
error_404:
  enable: false
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

post_meta:
  page: # Home Page
    date_type: both # created or modified or both 
    categories: true # true or false 
    label: true # true or false 
    author: true
    
  post:
    date_type: both # created or modified or both 
    categories: true # true or false 
    tags: true # true or false 
    label: true # true or false 
    author: true

# Display the article introduction on homepage
# 1: description
# 2: both (if the description exists, it will show description, or show the auto_excerpt)
# 3: auto_excerpt (default)
index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config

# Post
# --------------------------------------

# toc 
toc:
  enable: true
  number: true
  auto_open: true # auto open the sidebar

# Sponsor/reward
reward:
  enable: true
  QR_code:
    - img: 
      link:
      text: Wechat
    - img: 
      link:
      text: Alipay

# Related Articles
related_post:
  enable: true
  limit: 3 # Number of posts displayed
  date_type: created # or created or modified 

# figcaption 
photofigcaption: false

# anchor
# when you scroll in post, the URL will update according to header id.
anchor: true

# Displays outdated notice for a post
noticeOutdate:
  enable: false
  style: flat # style: simple/flat
  limit_day: 500 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# Share System 
# --------------------------------------

# Share.js
# https://github.com/overtrue/share.js
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo

# Comments System
# --------------------------------------

comments:
  # Up to two comments system, the first will be shown as default
  use: 
    - Disqus
  text: false # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: false # Display comment count in top_img

# disqus
# https://disqus.com/
disqus:
  shortname: 


# Footer Settings
# --------------------------------------
footer:
  owner:
    enable: true
    since: 2020
  custom_text: 

# Beautify/Effect 
# --------------------------------------

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00c4b6"
#   button_hover: "#FF7242"
#   text_selection: "#00c4b6"
#   link_color: "#99a9bf"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"

# The top_img settings of home page
# default: top img - full screen, site info - middle
# The position of site info, eg: 300px/300em/300rem/10% 
index_site_info_top:
# The height of top_img, eg: 300px/300em/300rem 
index_top_img_height: 21rem

# The user interface setting of category and tag page
# index - same as Homepage UI
# default - same as archives UI 
category_ui: 
tag_ui: 

# Website Background
# can set it to color or image 
# The formal of color: '#49B202'
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
# White color will be shown as default
background:

# Show the footer background image (same as top_img)
footer_bg: false

# the position of bottom right button/default unit: px 
rightside-bottom:


# Default display mode
# light (default) / dark
display_mode: light

# Beautify
beautify:
  enable: false
  field: post # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

# Global font settings
# Don't modify the following settings unless you know how they work 
font:
  font-family:
  code-font:

# Font settings for the site title and site subtitle
blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
  font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif


# Loading Animation
preloader: false

# aside
# --------------------------------------

aside:
  enable: true
  mobile: true # display on mobile
  position: left # left or right
  card_author:
    enable: true
    description:
    button:
      icon: fas fa-envelope
      text: Email
      link: 
  card_announcement:
    enable: true
    content: Don't ever give up
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or modified
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: YYYY MMMM 
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo: true


# Time difference between publish date and now
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: false
  publish_date: 

# Bottom right button
# --------------------------------------

# Read Mode
readmode: true

# dark mode
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false

# Lightbox 
# --------------------------------------
# You can only choose one, or neither

# medium-zoom
# https://github.com/francoischalifour/medium-zoom
medium_zoom: false

# fancybox
# http://fancyapps.com/fancybox/3/
fancybox: true

# Tag Plugins settings 
# --------------------------------------

# mermaid
# see https://github.com/knsv/mermaid
mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme: default

# Note (Bootstrap Callout)
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# other
# --------------------------------------

# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax: false

# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: false
  per_page: true

# Snackbar (Toast Notification)
# https://github.com/polonel/SnackBar
# top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: false
  position: bottom-left
  bg_light: '#49b1f5' # The background color of Toast Notification in light mode
  bg_dark: '#121212' # The background color of Toast Notification in dark mode

# https://instant.page/
# prefetch
instantpage: true

# Lazyload
# https://github.com/verlok/lazyload
lazyload:
  enable: true
  post: /image/loading.gif

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
# pwa:
#   enable: false
#   manifest: /image/pwa/manifest.json
#   theme_color: "#fff"
#   apple_touch_icon: /image/pwa/apple-touch-icon.png
#   favicon_32_32: /image/pwa/32.png
#   favicon_16_16: /image/pwa/16.png
#   mask_icon: /image/pwa/safari-pinned-tab.svg

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true

# Caches the contents in a fragment, speed up the generation 
fragment_cache: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
inject:
  head:
  # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# CDN
# Don't modify the following settings unless you know how they work
CDN:
  # main
  main_css: /css/index.css
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  main: /js/main.js
  utils: /js/utils.js

  # pjax
  pjax: https://cdn.jsdelivr.net/npm/pjax/pjax.min.js

  # comments


  # share
  sharejs: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js
  sharejs_css: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css

  # search
  local_search: /js/search/local-search.js
  algolia_js: /js/search/algolia.js
  algolia_search: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.js
  algolia_search_css: https://cdn.jsdelivr.net/npm/instantsearch.js@2.10.5/dist/instantsearch.min.css

  # math
  mermaid: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js


  lazyload: https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js
  instantpage: https://cdn.jsdelivr.net/npm/instant.page/instantpage.min.js
  typed: https://cdn.jsdelivr.net/npm/typed.js/lib/typed.min.js

  # photo
  fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js

  # snackbar
  snackbar_css: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
  snackbar: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js

  # effect
  anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js

  # fontawesome
  fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

  # justifiedGallery
  justifiedGallery_js: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/js/jquery.justifiedGallery.min.js
  justifiedGallery_css: https://cdn.jsdelivr.net/npm/justifiedGallery/dist/css/justifiedGallery.min.css

  # aplayer
  aplayer_css: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  aplayer_js: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  meting_js: https://cdn.jsdelivr.net/gh/metowolf/MetingJS@1.2/dist/Meting.min.js
